// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXeJ38xmhqGRgKookUO3026IZ7lxcl_y8',
    appId: '1:409157161858:web:2e9b09c1fce9c9cdd9759b',
    messagingSenderId: '409157161858',
    projectId: 'chat-app-df6f9',
    authDomain: 'chat-app-df6f9.firebaseapp.com',
    storageBucket: 'chat-app-df6f9.appspot.com',
    measurementId: 'G-25F57ZS4VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQEszX9PaV4XgzsBJV2r5hQ2M3tpHosDc',
    appId: '1:409157161858:android:13abc098cac8a8cfd9759b',
    messagingSenderId: '409157161858',
    projectId: 'chat-app-df6f9',
    storageBucket: 'chat-app-df6f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00AwhTr1OTAXVuh3UJB1qSAPPL4eFRaw',
    appId: '1:409157161858:ios:10bcd14d4e54bdddd9759b',
    messagingSenderId: '409157161858',
    projectId: 'chat-app-df6f9',
    storageBucket: 'chat-app-df6f9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA00AwhTr1OTAXVuh3UJB1qSAPPL4eFRaw',
    appId: '1:409157161858:ios:10bcd14d4e54bdddd9759b',
    messagingSenderId: '409157161858',
    projectId: 'chat-app-df6f9',
    storageBucket: 'chat-app-df6f9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXeJ38xmhqGRgKookUO3026IZ7lxcl_y8',
    appId: '1:409157161858:web:f76467ed6f2c52d2d9759b',
    messagingSenderId: '409157161858',
    projectId: 'chat-app-df6f9',
    authDomain: 'chat-app-df6f9.firebaseapp.com',
    storageBucket: 'chat-app-df6f9.appspot.com',
    measurementId: 'G-PBC48TVZ2E',
  );
}
